Models/Activit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace ActivityCenter.Models
{
    public class Activit
    {
        [Key]
        public int ActivitId{get;set;}
        
        [Required(ErrorMessage ="Must be present")]
        public string Title{get; set;}

        [Required]
        public string Tag{get;set;}

        [Required(ErrorMessage ="Must be at least two person")]
        [MinValue(2)]
        [MaxValue(100)]
        public int totalnumber{get;set;}
        public int? NumberOfMale{get;set;}
        
        public int? NumbeOfFemale{get;set;}

        [Required(ErrorMessage ="Must have an location")]
        public string Location{get;set;}    

        
        public int? MinAge{get;set;}

        
        public int? MaxAge{get;set;}


        [Required (ErrorMessage ="Must be present")]
        // [FutureDateAttribute (ErrorMessage ="Must be a future date")]


        public DateTime Date{get;set;}
        public int? Duration{get;set;}

        public double? price{get;set;}
        
        [Required (ErrorMessage ="Must be present")]
        public string Description{get;set;}

        public string DurationUnit{get;set;}
        public int UserId {get;set;}

        public List<Join> Guest{get;set;}
        public User Creator{get;set;}
        public DateTime CreatedAt {get;set;} = DateTime.Now;
        public DateTime UpdatedAt {get;set;} = DateTime.Now;
    }
}

public class FutureDateAttribute : ValidationAttribute
{
    public override bool IsValid(object value)
    {
        return value != null && (DateTime)value > DateTime.Now;
    }
}

public class MaxValueAttribute : ValidationAttribute
    {
        private readonly int _maxValue;

        public MaxValueAttribute(int maxValue)
        {
            _maxValue = maxValue;
        }

        public override bool IsValid(object value)
        {
            return (int) value <= _maxValue;
        }
    }

public class MinValueAttribute : ValidationAttribute
    {
        private readonly int _MinValue;

        public MinValueAttribute(int MinValue)
        {
            _MinValue = MinValue;
        }

        public override bool IsValid(object value)
        {
            return (int) value >= _MinValue;
        }
    }

Controllers/ActivitController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ActivityCenter.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace ActivityCenter.Controllers
{
    public class ActivitController : Controller
    {
        private ActivityCenterContext _context;
        private int? uid
        {
            get
            {
                return HttpContext.Session.GetInt32("UserId");
            }
        }
        
        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }
        public ActivitController(ActivityCenterContext context)
        {
            _context = context;
        }
        

        public IActionResult New()
        {
            


            return View();
        }

        [HttpPost("Create")]
        public IActionResult Create(Activit n)
        {
             if (ModelState.IsValid == false)
            {
                Console.WriteLine("Not valid");
                return View("New");
            }
            if(n.Duration ==0)
            {
                n.DurationUnit=null;
            }
           
            User CurrentUser= _context.Users
            .FirstOrDefault(l => l.UserId==uid);
            n.UserId = CurrentUser.UserId;
            
            _context.Activits.Add(n);
            _context.SaveChanges();
            return RedirectToAction("MainPage","Home");

        }
        

        [HttpPost("Reserve")]
        public IActionResult Reserve(Join n)
        {
            
            _context.Joins.Add(n);
            _context.SaveChanges();
            return RedirectToAction("Home");

        }
        [HttpPost("UnReserve")]
        public IActionResult UnReserve(Join n)
        {
            Join one =_context.Joins
            .SingleOrDefault(d => d.ActivitId == n.ActivitId && d.UserId == n.UserId); 
            _context.Joins.Remove(one);
            _context.SaveChanges();
            return RedirectToAction("Home");

        }

        [HttpGet("{ActivitId}/delete")]
        public IActionResult Delete(int ActivitId)
        {
            Activit one = _context.Activits
            .SingleOrDefault(d => d.ActivitId == ActivitId); 
           _context.Activits.Remove(one);
           _context.SaveChanges();
           return RedirectToAction("Home");
        }

        [HttpGet("{Activits}")]
        public IActionResult Detail(int Activits)
        {

            ViewBag.Ac= _context.Activits
            .Include(l => l.Creator)
            .Include(l => l.Guest)
            .ThenInclude(l => l.User)
            .FirstOrDefault(d => d.ActivitId == Activits)
            ;
            
            ViewBag.AllGuest = _context.Users
            .Include(l=>l.Attend)
            .ThenInclude(l => l.Activit)
            .Where(l=>l.Attend.Any(l=>l.Activit.ActivitId==Activits))
            .ToList();

             ViewBag.Exceptions = _context.Activits
            .Include(l => l.Guest)
            .ThenInclude(l =>l.User)
            .Where(l => l.Guest.Any(l => l.User.UserId == uid ))
            .ToList();

            ViewBag.Id = uid;


           return View("Detail");
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ActivityCenter.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace ActivityCenter.Controllers
{
    public class HomeController : Controller
    {
        private ActivityCenterContext _context;
        private int? uid
        {
            get
            {
                return HttpContext.Session.GetInt32("UserId");
            }
        }
        
        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }

        public HomeController(ActivityCenterContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
public IActionResult _login()
        {
            return View();
        }
       
        [HttpPost("Login")]
        public IActionResult Login(LoginUser loginUser)
        {
           if (ModelState.IsValid == false)
            {
                return View("_login");
            }


            Phone dbphone = _context.Phones.FirstOrDefault(user => user.Number == loginUser.LoginName);
             if (dbphone == null)
            {
                ModelState.AddModelError("LoginName", "Phone not found.");
                                return View("_login");

            }

            User dbUser = _context.Users.FirstOrDefault(user => user.PhoneId == dbphone.PhoneId);
            if (dbUser == null)
            {
                ModelState.AddModelError("LoginName", "Phone not found.");
                                return View("_login");

            }
        

           
            PasswordHasher<LoginUser> hasher = new PasswordHasher<LoginUser>();
            PasswordVerificationResult pwCompareResult = hasher.VerifyHashedPassword(loginUser, dbUser.Password, loginUser.LoginPassword);
            if (pwCompareResult == 0)
            {
                ModelState.AddModelError("LoginName", "incorrect credentials.");
                return View("_login"); 
            }
            HttpContext.Session.SetInt32("UserId", dbUser.UserId);
            return RedirectToAction("MainPage");
            
        }

        public IActionResult MainPage()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index");
            }
            ViewBag.user = _context.Users
            .Include(User => User.UserLocation)
            .SingleOrDefault(l => l.UserId == uid);
            
            string usercity = ViewBag.user.UserLocation.city;
            string userstate = ViewBag.user.UserLocation.state_name;
            
            ViewBag.act= _context.Activits.Include(l => l.Creator.UserLocation)
            .Where(l=>l.Creator.UserLocation.city==usercity && l.Creator.UserLocation.state_name==userstate);
            

            return View();
        }

       
        [HttpGet("Logout")]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Activit/Detail.cshtml
  <nav class="navbar navbar-light bg-light">
  <a class="navbar-brand">Dojo Acitiviy Center</a>
  <p class="form-inline">
     <a asp-action="Home" asp-controller="Activit">Home</a> <a asp-action="Logout" asp-controller="Home">Logout</a></p>
    
</nav>

@model Activit

<h1>
    @ViewBag.Ac.Title</h1>


                        @if (ViewBag.Id  == ViewBag.Ac.Creator.UserId )
                            {
                             <a href="/@ViewBag.Ac.ActivitId/delete"> <button>Delete</button> </a>
                            }
                            else if(ViewBag.Exceptions.Contains(ViewBag.Ac)==false){
                            
                                <form asp-action="Reserve" asp-controller="Activit">
                                    <input type="hidden" asp-for="ActivitId" value="@ViewBag.Ac.ActivitId">
                                    <input type="hidden" asp-for="UserId" value="@ViewBag.Id">
                                    <input type="Submit" name="" Value="Join">
                                </form>
                            
                            }
                            else{
                                
                                <form asp-action="UnReserve" asp-controller="Activit">
                                    <input type="hidden" asp-for="ActivitId" value="@ViewBag.Ac.ActivitId">
                                    <input type="hidden" asp-for="UserId" value="@ViewBag.Id">
                                    <input type="Submit" name="" Value="Leave">
                                </form>
                            
                            }

<h2>Event Corrdinator : @ViewBag.Ac.Creator.Name</h2>

<h3>Description:</h3>
<p>@ViewBag.Ac.Description</p>
<h3>Participants</h3>
@foreach (var i in ViewBag.AllGuest)
{
    <p>@i.Name</p>
}

Views/Activit/Home.cshtml
<div class="container">
  <nav class="navbar navbar-light bg-light">
  <a class="navbar-brand">Dojo Acitiviy Center</a>
  <p class="form-inline">
      Welcome,@ViewBag.Name!  
      <a asp-action="Logout" asp-controller="Home">Logout</a></p>
    
</nav>
@model Join
 
    <div class="row mt-5">
        <table class="table table-striped">
                    <tr>
                        <th>Activity</th>
                        <th>Date and Time</th>
                        <th>Durations</th>
                        <th>Event Corrdinator</th>
                        <th>No of Participants</th>
                        <th>Actions</th>
                    </tr>
                    @foreach(var l in ViewBag.AllAc)
                    {
                        <tr>
                            <td><a href="/@l.ActivitId">@l.Title</a></td>
                            <td>@l.Date.ToString("MM/dd") at @l.Time.ToShortTimeString()</td>
                            <td>@l.Duration @l.DurationUnit</td>
                            <td>
                                @l.Creator.Name</td>
                            <td>@l.Guest.Count</td>


                            @if (l.UserId == ViewBag.Id )
                            {
                            <td> <a href="/@l.ActivitId/delete">Delete</a></td>
                            }
                            else if(ViewBag.Exceptions.Contains(l)==false){
                            <td>
                                <form asp-action="Reserve" asp-controller="Activit">
                                    <input type="hidden" asp-for="ActivitId" value="@l.ActivitId">
                                    <input type="hidden" asp-for="UserId" value="@ViewBag.Id">
                                    <input type="Submit" name="" Value="Join">
                                </form>
                            </td>
                            }
                            else{
                                <td>
                                <form asp-action="UnReserve" asp-controller="Activit">
                                    <input type="hidden" asp-for="ActivitId" value="@l.ActivitId">
                                    <input type="hidden" asp-for="UserId" value="@ViewBag.Id">
                                    <input type="Submit" name="" Value="Leave">
                                </form>
                            </td>
                            }
                        </tr>
                    }
    </table>    

    <a class="float-right" asp-action="New", asp-controller="Activit"><button>Add New Activity</button></a>
</div>

Views/Activit/New.cshtml
  <nav class="navbar navbar-light bg-light">
  <a class="navbar-brand">Dojo Acitiviy Center</a>
  <p class="form-inline">
     <a asp-action="Home" asp-controller="Activit">Home</a> <a asp-action="Logout" asp-controller="Home">Logout</a></p>
    
</nav>
@model Activit
<form asp-action="Create" asp-controller="Activit">
     <div class="form-group">
    <label asp-for="Title"></label>
    <span asp-validation-for="Title" class="text-danger font-weight-bold"></span>
    <input asp-for="Title">

     <label asp-for="Tag"></label>
    <span asp-validation-for="Tag" class="text-danger font-weight-bold"></span>
    <select asp-for="Tag">
         <option value="chihe">Food & Drink</option>
         <option value="wanle">Entertainment</option>
         <option value="jsxx">Excercise & Study</option>
         <option value="others">Other</option>
    </select>
    </div>

     <div class="form-group">
    <label asp-for="Date"></label>
    <span asp-validation-for="Date" class="text-danger font-weight-bold"></span>
    <input asp-for="Date" />
    
     <label asp-for="Location"></label>
    <span asp-validation-for="Location" class="text-danger font-weight-bold"></span>
    <input asp-for="Location" />

    <label asp-for="Duration"></label>
    <span asp-validation-for="Duration" class="text-danger font-weight-bold"></span>
    <input asp-for="Duration"  />
    <select asp-for="DurationUnit">
         <option value="Hours">Hours</option>
         <option value="Minutes">Minutes</option>
         <option value="Days">Days</option>
    </select>
    </div>

     <div class="form-group">
     <label asp-for="totalnumber">Total Number of Participates</label>
    <span asp-validation-for="totalnumber" class="text-danger font-weight-bold"></span>
    <input asp-for="totalnumber" />
   <label asp-for="NumberOfMale">Total Number of Male</label>
    <span asp-validation-for="NumberOfMale" class="text-danger font-weight-bold"></span>
    <input asp-for="NumberOfMale" />
   <label asp-for="NumbeOfFemale">Total Number of Female</label>
    <span asp-validation-for="NumbeOfFemale" class="text-danger font-weight-bold"></span>
    <input asp-for="NumbeOfFemale" />
  
    
    </div>
    

     <div class="form-group">
            <label asp-for="MinAge"></label>
    <span asp-validation-for="MinAge" class="text-danger font-weight-bold"></span>
    <input asp-for="MinAge" />
    <label asp-for="MaxAge"></label>
    <span asp-validation-for="MaxAge" class="text-danger font-weight-bold"></span>
    <input asp-for="MaxAge" />
<label asp-for="price"></label>
    <span asp-validation-for="price" class="text-danger font-weight-bold"></span>
    <input asp-for="price" />
    
     </div>

     <div class="form-group">
    <label asp-for="Description">Description:</label><br>
    <span asp-validation-for="Description" class="text-danger font-weight-bold"></span>
    <textarea asp-for="Description" id="" cols="60" rows="10"></textarea>
    </div>
    <input type="Submit" name="" id="" value="Create Activity">
    
</form>